language: java
jdk: openjdk16

services:
  - postgresql

addons:
  postgresql: "12.7"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    -PGPORT=5432
    -PGUSER=travis

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
